[toolchain]
anchor_version = "0.31.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
merkle_distributor = "11111111111111111111111111111111"

[programs.devnet]
merkle_distributor = "8LMVzwtrcVCLJPFfUFviqWv49WoyN1PKNLd9EDj4X4H4"

[programs.mainnet]
merkle_distributor = "8LMVzwtrcVCLJPFfUFviqWv49WoyN1PKNLd9EDj4X4H4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./keys/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

